"""motte_skill：M5-T06 的 Skill 三类形态、不可变版本与安全导入。"""

__version__ = "0.1.0"

from .importer import (
    ContentAddressedMemoryStore,
    ImportedResource,
    SkillImportCode,
    SkillImportError,
    SkillImportReport,
    import_skill,
    ingest_resources,
)
from .manifest import SkillManifest
from .registry import SkillRegistry
from .versions import (
    INJECTION_MODES,
    SKILL_KINDS,
    SKILL_LIFECYCLES,
    SKILL_SCHEMA_VERSION,
    SkillBinding,
    SkillContentHashMismatch,
    SkillDependency,
    SkillDependencyNotPinned,
    SkillDeprecated,
    SkillDraft,
    SkillEntrypoint,
    SkillError,
    SkillFixtureRef,
    SkillNotFound,
    SkillPermissions,
    SkillResource,
    SkillSetRef,
    SkillVersion,
    SkillVersionConflict,
    deprecate_skill,
    is_deprecation_transition,
    is_exact_pin,
    publish_skill,
    select_skills,
    skill_content_hash,
    skill_version_transition,
    verify_dependency_refs,
    verify_resources,
)

__all__ = [
    "INJECTION_MODES",
    "SKILL_KINDS",
    "SKILL_LIFECYCLES",
    "SKILL_SCHEMA_VERSION",
    "ContentAddressedMemoryStore",
    "ImportedResource",
    "SkillBinding",
    "SkillContentHashMismatch",
    "SkillDependency",
    "SkillDependencyNotPinned",
    "SkillDeprecated",
    "SkillDraft",
    "SkillEntrypoint",
    "SkillError",
    "SkillFixtureRef",
    "SkillImportCode",
    "SkillImportError",
    "SkillImportReport",
    "SkillManifest",
    "SkillNotFound",
    "SkillPermissions",
    "SkillRegistry",
    "SkillResource",
    "SkillSetRef",
    "SkillVersion",
    "SkillVersionConflict",
    "__version__",
    "deprecate_skill",
    "import_skill",
    "ingest_resources",
    "is_deprecation_transition",
    "is_exact_pin",
    "publish_skill",
    "select_skills",
    "skill_content_hash",
    "skill_version_transition",
    "verify_dependency_refs",
    "verify_resources",
]
